### PR TITLE
Cross platform build missing site packages fix

### LINKED ISSUE #2: FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/RTModel/bin/Reader'
I encountered an issue while running the following part: `rtm.run()`. The error message I received is as follows:

FileNotFoundError: [Errno 2] No such file or directory: ‘/usr/local/lib/python3.10/dist-packages/RTModel/bin/Reader’

Could you please guide me on how to resolve this?

### PR DESCRIPTION
**Pull request by golmschenk**
Applies the fix mentioned [here](https://github.com/valboz/RTModel/pull/1#issuecomment-2041817057). Fixes #2.

### CODE REVIEW

**Comment by golmschenk** [comment]
Uh oh, during the fix I was going to send out, I had temporarily added back in the double install method. I will remove that now. You will probably want to test it for Windows again without that double install method. I will double check on Colab.

**Comment by golmschenk** [comment]
Colab installation still works fine. Please confirm the Windows install again with your specific setup that failed previously before merging. The CI runner Windows works ok, but there are several possible install approaches on Windows.

**Comment by valboz** [comment]
Hi, I confirm that it works correctly on my setup. If you are ready for the pull request, I would approve it. Thanks again

**Comment by golmschenk** [comment]
@valboz, this PR should be good to go. Thanks!

**Pull request merged**
